### PR TITLE
Fix variant attribute validation since Filament 3.3.12

### LINKED ISSUE #2190: Validation error when saving attribute_data from a single variant product resource
- Lunar version: 1.0.0-beta20
- Laravel Version: 11.44.7
- PHP Version: 8.3.20
- Database Driver & Version: MySQL 8

### Expected Behaviour:
Saving a single variant product with custom attributes (for example, a number field) should work

### Actual Behaviour:
This pull request https://github.com/lunarphp/lunar/pull/2154 fixed a bug where custom attributes of a single variant product would trigger validation errors when saving the product.

Since Filament 3.3.12, this doesn't work anymore and we are back in the previous behaviour.

### Steps To Reproduce:
- Install the starterkit (with the latest version of Filament)
- create a custom Number attribute for variants
- add this attribute to a product type
- create a product
- save -> validation error
- composer require filament/filament:3.3.11 -W
- save -> it works

## Temporary fix
Lock Filament version in the project, by running: composer require filament/filament:3.3.11 -W

### PR DESCRIPTION
**Pull request by fredmarmillod**
## Description

This PR fixes a regression in variant attribute validation that occurred after Filament version 3.3.12, specifically related to [Filament PR #16081](https://github.com/filamentphp/filament/pull/16081/files).

## Issue

This PR fixes #2190  

## Changes

- **AttributeData.php**: Added  callback to convert FieldType objects to their actual values before validation
- **EditProductTest.php**: Updated test to use  field type with boolean values to properly test the fix

## Root Cause

Since Filament 3.3.12, the  callback wasn't being called consistently during form validation, causing FieldType objects to be passed directly to validation instead of their primitive values.

## Testing

Update the "can edit variant attributes" test in EditProductTest.php and change the type of the attribute to Toogle. This will make the test fail.

Add the changes from AttributeData.php and it will pass.

### CODE REVIEW

File: tests/admin/Feature/Filament/Resources/ProductResource/Pages/EditProductTest.php [hunk 1]
```diff
@@ -59,12 +60,12 @@
...
     $component->fillForm([
         'variant' => [
-            $attribute->handle => new \Lunar\FieldTypes\Text('Hello'),
+            $attribute->handle => new \Lunar\FieldTypes\Toggle(true),
         ],
     ])->call('save')
         ->assertHasNoFormErrors();
 
-    expect($variant->refresh()->attr($attribute->handle))->toBe('Hello');
+    expect($variant->refresh()->attr($attribute->handle))->toBe(true);
```
Comment (wychoong) [inline tests/admin/Feature/Filament/Resources/ProductResource/Pages/EditProductTest.php]: can you add more assertions for different field types

File: packages/admin/src/Support/Forms/AttributeData.php [hunk 2]
```diff
@@ -61,6 +61,14 @@ public function getFilamentComponent(Attribute $attribute): Component
 
                 return $state;
             })
+            ->mutateStateForValidationUsing(function ($state) {
+                // Convert FieldType objects to their actual values for validation
```
Comment (wychoong) [inline packages/admin/src/Support/Forms/AttributeData.php]: remove comment

**Review by wychoong — COMMENTED** [review]
should pin filament version to ^3.3.12

**Comment by glennjacobs** [comment]
> should pin filament version to ^3.3.12

I've already bumped the Filament version. Updating the branch should bring it in.

File: tests/admin/Feature/Filament/Resources/ProductResource/Pages/EditProductTest.php (hunk 1 above)
Comment (fredmarmillod) [reply tests/admin/Feature/Filament/Resources/ProductResource/Pages/EditProductTest.php]: I've updated the test to use dataset, but I wasn't able to make it work with non primitive types, for example: TranslatedText.

**Review by glennjacobs — APPROVED** [review]

**Comment by glennjacobs** [comment]
Thanks
