### PR TITLE
fix: product type table saved search

### LINKED ISSUE #664: Product Type saved search isnt working
- Lunar version: 0.1.1

### Expected Behaviour:

There is notif message `Search saved` and show the saved search under the search field.

### Actual Behaviour:

Multiple time click the `Saved Search` still does not work

### Steps To Reproduce:

1. Go to product type
2. Type anything in the search field
3. click save search button on the right of search field
4. and save with the search with the name

### PR DESCRIPTION
**Pull request by Aslam97**
fixed #664

### CODE REVIEW

**Review by markmead — DISMISSED** [review]
All working.

File: packages/admin/src/Http/Livewire/Components/Products/Tables/ProductTypesTable.php [hunk 1]
```diff
@@ -45,6 +59,67 @@ public function build()
...
+        ]);
+
+        auth()->getUser()->savedSearches()->create([
+            'name' => $this->savedSearchName,
+            'term' => $this->query,
+            'component' => $this->getName(),
+            'filters' => $this->filters,
+        ]);
+
+        $this->notify('Search saved');
```
Comment (alecritson) [inline packages/admin/src/Http/Livewire/Components/Products/Tables/ProductTypesTable.php:97]: There should be a translation for this:

```
__('adminhub::notifications.saved_searches.saved')
```

Comment (Aslam97) [reply packages/admin/src/Http/Livewire/Components/Products/Tables/ProductTypesTable.php]: @alecritson updated

**Review by glennjacobs — APPROVED** [review]
